import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"5 demonios",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/5%20demonios.mp3?alt=media&token=6f3aaabe-8f04-4215-b869-b272932e19d2",
            active: true,
        },
        {
            name:"ahijado de oro",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://mp3.chillhop.com/serve.php/?mp3=22794",
            active: false,
        },
        {
            name:"tropa del infierno",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://ice2.somafm.com/seventies-128-mp3",
            active: false,
        },
        {
            name:"chaparro v2",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streaming.hotmixradio.fm/hotmixradio-80-128.mp3?from=tunein",
            active: false,
        },
        {
            name:"chelino",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: " http://streaming.hotmixradio.fr/hotmixradio-lounge-128.mp3?from=tunein",
            active: false,
        },
        {
            name:"chiricuazo",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "http://mp3.ffh.de/ffhchannels/hq90er.mp3?amsparams=playerid:RTFFHTunein;skey:1581676248",
            active: false,
        },
        {
            name:"chris trevino",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "http://sunshinelive.hoerradar.de/sunshinelive-live-mp3-hq?sABC=5r46783o%230%231o70r21o79929956s30p83402120q5q4%23gharva&amsparams=playerid:tunein;skey:1581676603",
            active: false,
        },
        {
            name:"comandante gafe",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "http://cob-ais.leanstream.co/CINDFM-MP3?args=tunein_01",
            active: false,
        },
        {
            name:"cuadro del terror",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "http://los.cdnstream.com/1102_128",
            active: false,
        },
        {
            name:"delinqueando",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://listen-funkids.sharp-stream.com/funkids.mp3?device=tunein",
            active: false,
        },
        {
            name:"despierta",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://stream.cdm-chillout.com:8020/stream-mp3-Chill",
            active: false,
        },
        {
            name:"3 letras",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://playerservices.streamtheworld.com/api/livestream-redirect/XEQR_FM.mp3?tdtok=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImZTeXA4In0.eyJpc3MiOiJ0aXNydiIsInN1YiI6IjIxMDY0IiwiaWF0IjoxNTgxNjc3NjI5LCJ0ZC1yZWciOmZhbHNlfQ.OMSwENr75iagPVR3nvwThrfNUw1lLuC7x1jCWc5qOAo",
            active: false,
        },
        {
            name:"el adrian",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://stream.soundstorm-radio.com:8000/stream1",
            active: false,
        },
        {
            name:"el blue",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://ice2.somafm.com/seventies-128-mp3",
            active: false,
        },
        {
            name:"chisquiado",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://pool.defjay.com/DEFJAY.mp3",
            active: false,
        },
        {
            name:"el coahuila",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://strm112.1.fm/reggae_mobile_mp3",
            active: false,
        },
        {
            name:"el griego",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://fm02-ice.stream.khz.se/fm02_mp3",
            active: false,
        },
        {
            name:"el memito",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://cms.stream.publicradio.org/cms.mp3?aw_0_1st.playerid=RadioTime&aw_0_1st.skey=1582304573&aw_0_1st.platform=tunein",
            active: false,
        },
        {
            name:"el muneco",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://mainstream.amazingradios.com:8000/blues128",
            active: false,
        },
        {
            name:"el pena",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://live-radio02.mediahubaustralia.com/JAZW/mp3/",
            active: false,
        },
        {
            name:"el piko",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s1-webradio.antenne.de/hits-fuer-kids/stream/mp3?aw_0_1st.playerid=tunein.com",
            active: false,
        },
        {
            name:"el R",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/5%20demonios.mp3?alt=media&token=6f3aaabe-8f04-4215-b869-b272932e19d2",
            active: true,
        },
        {
            name:"el rodriguez",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://mp3.chillhop.com/serve.php/?mp3=22794",
            active: false,
        },
        {
            name:"el sobrino",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://ice2.somafm.com/seventies-128-mp3",
            active: false,
        },
        {
            name:"el solorio",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streaming.hotmixradio.fm/hotmixradio-80-128.mp3?from=tunein",
            active: false,
        },
        {
            name:"el topo",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: " http://streaming.hotmixradio.fr/hotmixradio-lounge-128.mp3?from=tunein",
            active: false,
        },
        {
            name:"en nadie confio",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "http://mp3.ffh.de/ffhchannels/hq90er.mp3?amsparams=playerid:RTFFHTunein;skey:1581676248",
            active: false,
        },
        {
            name:"equipado pa la guerra",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "http://sunshinelive.hoerradar.de/sunshinelive-live-mp3-hq?sABC=5r46783o%230%231o70r21o79929956s30p83402120q5q4%23gharva&amsparams=playerid:tunein;skey:1581676603",
            active: false,
        },
        {
            name:"evelyn piedras negras",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "http://cob-ais.leanstream.co/CINDFM-MP3?args=tunein_01",
            active: false,
        },
        {
            name:"flako mendoza",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "http://los.cdnstream.com/1102_128",
            active: false,
        },
        {
            name:"franky esqueda",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://listen-funkids.sharp-stream.com/funkids.mp3?device=tunein",
            active: false,
        },
        {
            name:"franky joya",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://stream.cdm-chillout.com:8020/stream-mp3-Chill",
            active: false,
        },
        {
            name:"fumando un blunt",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://playerservices.streamtheworld.com/api/livestream-redirect/XEQR_FM.mp3?tdtok=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImZTeXA4In0.eyJpc3MiOiJ0aXNydiIsInN1YiI6IjIxMDY0IiwiaWF0IjoxNTgxNjc3NjI5LCJ0ZC1yZWciOmZhbHNlfQ.OMSwENr75iagPVR3nvwThrfNUw1lLuC7x1jCWc5qOAo",
            active: false,
        },
        {
            name:"jimmy galvan",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://stream.soundstorm-radio.com:8000/stream1",
            active: false,
        },
        {
            name:"la muneca",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://ice2.somafm.com/seventies-128-mp3",
            active: false,
        },
        {
            name:"let em hate",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://pool.defjay.com/DEFJAY.mp3",
            active: false,
        },
        {
            name:"3 plebes",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://strm112.1.fm/reggae_mobile_mp3",
            active: false,
        },
        {
            name:"memito y el flako",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://fm02-ice.stream.khz.se/fm02_mp3",
            active: false,
        },
        {
            name:"memito y el jimmy",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://cms.stream.publicradio.org/cms.mp3?aw_0_1st.playerid=RadioTime&aw_0_1st.skey=1582304573&aw_0_1st.platform=tunein",
            active: false,
        },
        {
            name:"mike infona",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://mainstream.amazingradios.com:8000/blues128",
            active: false,
        },
        {
            name:"ni bueno ni malo",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://live-radio02.mediahubaustralia.com/JAZW/mp3/",
            active: false,
        },
        {
            name:"no todos son buenos",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s1-webradio.antenne.de/hits-fuer-kids/stream/mp3?aw_0_1st.playerid=tunein.com",
            active: false,
        },
        {
            name:"operativa gafe",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://playerservices.streamtheworld.com/api/livestream-redirect/XEQR_FM.mp3?tdtok=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImZTeXA4In0.eyJpc3MiOiJ0aXNydiIsInN1YiI6IjIxMDY0IiwiaWF0IjoxNTgxNjc3NjI5LCJ0ZC1yZWciOmZhbHNlfQ.OMSwENr75iagPVR3nvwThrfNUw1lLuC7x1jCWc5qOAo",
            active: false,
        },
        {
            name:"patron del mal",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://stream.soundstorm-radio.com:8000/stream1",
            active: false,
        },
        {
            name:"patrullando voy",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://ice2.somafm.com/seventies-128-mp3",
            active: false,
        },
        {
            name:"por mi estilo",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://pool.defjay.com/DEFJAY.mp3",
            active: false,
        },
        {
            name:"profesion bandido",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://strm112.1.fm/reggae_mobile_mp3",
            active: false,
        },
        {
            name:"san judas tadeo",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://fm02-ice.stream.khz.se/fm02_mp3",
            active: false,
        },
        {
            name:"santa muerte",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://cms.stream.publicradio.org/cms.mp3?aw_0_1st.playerid=RadioTime&aw_0_1st.skey=1582304573&aw_0_1st.platform=tunein",
            active: false,
        },
        {
            name:"tanque puentes",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://mainstream.amazingradios.com:8000/blues128",
            active: false,
        },
        {
            name:"mi vida loka",
            artist: "C.E.",
            cover: "https://firebasestorage.googleapis.com/v0/b/makabelicomusic-55f97.appspot.com/o/icon.png?alt=media&token=c28ce4ba-ec40-4e98-a5e8-896513beb2a8",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://live-radio02.mediahubaustralia.com/JAZW/mp3/",
            active: false,
        },   
    ];
}

export default chillHop;

